### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by Silex**
Hello,

Maybe don't merge this _immediatly_ as there's likely other changes incoming, which I'm not sure what to do with... namely:

- What to do with `sp-pair-overlay-face` inside the code? remove it? replace it with what?
- Is it ok to update the table in `etable-mark-row` like I do?
- I want it that when I press 'm' (mark), it goes to the next row. Again, should I code this in etable-mark-row?

Alors, please comment on the implementation of `etable-unmark-all` and `etable-toggle-marks` which are sketchy at best :)

### CODE REVIEW

**Comment by Silex** [comment]
@Fuco1: ahem, comments? :smile:

**Comment by Fuco1** [comment]
Looks good, I've added some comments.

**Comment by Silex** [comment]
Ah, cool. I thought `etable-toogle-marks` was implemented in a silly way, but maybe not :)

**Comment by Silex** [comment]
Alright, you can merge this already. I still don't know what to do about `sp-pair-overlay-face` tho.

**Comment by Fuco1** [comment]
If I use it somewhere, just replace it with some etable face (if it doesn't exist add some)

**Comment by Silex** [comment]
Alright the faces replacement was easier than expected.

I'll change for `etable-next-row` and we are good.

**Comment by Silex** [comment]
There's this weird bug that I can't fix... going next/previous rows always moves one column to the right... any idea?

**Comment by Fuco1** [comment]
The next/previous row targets the target column, which is set when creating the view (for example, for a dired listing it should always hop to the column with the file name).

**Comment by Silex** [comment]
Oh, then I guess the way I create it makes it so the target colum is always the next one:

```
(setq mytable (etable-create-table [
[ "REPOSITORY"              "TAG"                 "IMAGE ID"            "CREATED"             "VIRTUAL SIZE" ]
[ "projectile-testdata"     "latest"              "87ae09896a5c"        "11 days ago"         "1.111 GB" ]
[ "debian"                  "unstable"            "659dbcf1a318"        "3 weeks ago"         "123 MB" ]
[ "debian"                  "8"                   "835c4d274060"        "3 weeks ago"         "122.6 MB" ]
[ "debian"                  "8.0"                 "835c4d274060"        "3 weeks ago"         "122.6 MB" ]
[ "debian"                  "jessie"              "835c4d274060"        "3 weeks ago"         "122.6 MB" ]
]))
(etable-draw mytable 3428)
```

Here pressing `n` moves diagnonally from top left to bottom right...

Can you give me a basic setup of the above where `n` either always goes down, or where it always uses the `IMAGE ID` column?

Also, while we're at it, is there support to actually render the first row as column header (e.g not selectable)?

**Comment by Fuco1** [comment]
Using the `etable-table-column-model` you can set margins and goal column.  Using `etable-table-model` you can set column IDs, which are headers... but it seems they don't render yet :) (and really, they should be part of `etable-table-column` or `column-model`)

**Comment by Fuco1** [comment]
The diagonal movement behaviour is probably a bug due to the goal column not being set in the default implementation of the column model (it inits to `nil` which causes I-don't-know-what in the movement functions... probably some nonsense---maybe it should just default to 0)

**Comment by Silex** [comment]
Alright, setting it to 0 indeed makes it behave more sanely.

**Comment by Silex** [comment]
@Fuco1: are we good?

**Comment by Fuco1** [comment]
Yea, we good. Merging ;)

**Comment by Silex** [comment]
:+1: 

I'll soon want the columns header to be displayed so probably another PR will come by then :) if you have  pointers about where I should start looking don't be shy ;)

**Pull request merged**
