### PR TITLE
Moar improvements

### PR DESCRIPTION
**Pull request by Silex**
Hello,

Don't merge this yet... more commits are following, mostly resulting on your input about the following:
1. The code uses `cl-` a lot, shall I try and replace it all with dash or do I add cl-lib as a dependency?
2. I'm trying to build examples, can you please check them... and if you have more please attach them here and I'll add them. The "advanced" one doesn't work yet, I created it from your "example" file... the error is "non applicable-method etable-get-column-count etable-table-model", do you know what I should do to fix it? Maybe we remove the advanced example for now?
3. The headers never show, I'm not sure where to fiddle with that to make them show... any idea?
4. I'm considering implementing automatic resizing of columns, so far I'm writing a function `etable-auto-size-columns` which will `etable-set-width` each column to its maximum length. Does it make sense or is it possible to implement this directly in the column? maybe with `:width 'auto` or something.
5. The naming is somewhat confusing... e.g `etable-table-column` is a column and `etable-table-column-model` is a group of columns... are you ok with heavy renaming? e.g `etable-column-group` or something.

Let's start with this and probably more questions will follow :D

### CODE REVIEW

**Comment by Fuco1** [comment]
1) Since we already use eieio which is one of them "overkill packages", I guess I'm fine with it, but prefer dash when possible.
2) Examples are a good idea indeed.  Dunno about the error, but it's only used on 3 or 4 places.  I would guess it is being applied to a type not defining the method.
3) The rendering was probably never implemented.  Adding a single loop somewhere before the one drawing the table should do the trick (in `etable-update`). To make your own custom headers, you'd need to extend the default table model class and implement `etable-get-column-name` appropriately.
4) So I understand it you want the column width be the same as the widest element in the column.  You would probably need to pre-render all the values for the column, find the longest one and then use that as the cut-out value.  The cells are shortened in`etable-update`.  So the inner loop would need to be either changed or you'd run the renderers twice.  You can make the `:auto` switch determine the width that way.  Remember that the cell-renderer is unaware of any width limitations and should always return the entire content.  There's a lot of opportunity for caching too, if things get too slow.
5) The `-model` naming is a convention of MVC.  Column model is something you would read to get information on how to build the columns, see for example http://docs.oracle.com/javase/7/docs/api/javax/swing/table/TableColumnModel.html

**Comment by Silex** [comment]
Wow, thanks great answer! I'll start hacking :)

**Comment by Silex** [comment]
@Fuco1: hum, I wonder what's the rational for having the columns name inside the `etable-default-table-model`. Doesn't it make more sense to have them in `etable-table-column`? Look at the dired example, it's kind of awkward right now no?

Not a big deal just wondering.

**Comment by Fuco1** [comment]
It probably makes more sense to put the header name into the column yes.

I think the idea was that if you don't specify the names in the column, the table should derive them from the model somehow as a backup.

So if the column has a header property set, we should use it, otherwise fall back to `etable-get-column-name` (which, if you don't set `column-ids` it falls back to A, B, C, D, ... from the abstract model)

I probably just didn't get to implementing the header property in the column.

**Comment by Fuco1** [comment]
Sorry, I mean fall back to `columns-ids`, the entry point to generate the name should still be `etable-get-column-name` from the model, only that it first looks in the column data.

**Comment by Fuco1** [comment]
Hmm, now that I look at it further, it's a bit odder still.  The `etable-get-column-name` is in the `etable-table-model` not in the `etable-table-column-model` where it logically belongs.

The table model represents the data, it can have more or less columns than what will be rendered.  The mapping between rendered columns and the data columns is the column model.  This way you can reuse data over multiple tables and still render them differently.

Java has it in the TableModel not TableColumnModel but I don't understand the logic behind it. I think it only serves as a fallback.

We could probably move it from the table model to the column model, as it is not used anywhere as of now.

**Comment by Silex** [comment]
Okay, I'll see how easy it is to move it to the column model :) Thanks for the feedback.

**Comment by Silex** [comment]
In the meantime I found `tabulated-list`... I'm sorry but I'm switching it it, it's much simpler and fits existing user experience. You can merge what you like from this PR :)

**Comment by Fuco1** [comment]
> In the meantime I found `tabulated-list`... I'm sorry but I'm
> switching it it, it's much simpler and fits existing user
> experience. You can merge what you like from this PR :)

tabulated-list was one of the evils I was trying to replace.  Its only
advantage is that it already works :D

Very well, use what works :)

-- 
Best regards,
  Matúš Goljer

**Comment by Silex** [comment]
I agree it's less well designed that Etable... but it's so simple and has everything I need atm.

Maybe later I'll switch back to ETable when I get bit by tabulated-list :)

**Pull request closed without merging**
